version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-usuario
    environment:
      POSTGRES_DB: meubanco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5400:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: app-python
    ports:
      - "5000:80"  # porta externa : porta do container (FastAPI roda na 80)
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/meubanco
      DEBUG: "false"
      LOG_FILE: /app/logs/app.log
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
