version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-usuario
    environment:
      POSTGRES_DB: meubanco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5400:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-projeto-1
    ports:
      - "5672:5672"     # Porta padrão para aplicações
      - "15672:15672"   # Interface web de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - db
  app:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: app-python
    ports:
      - "5000:80"  # porta externa : porta do container (FastAPI roda na 80)
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/meubanco
      DEBUG: "false"
      LOG_FILE: /app/logs/app.log
      PYTHONUNBUFFERE: "1"
    tty: true
    stdin_open: true
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started  
    networks:
      - app-network
    # entrypoint: /app/entrypoint.sh

  celery_worker:
    build: ./
    volumes:
        - .:/app
    command: celery -A controller.CeleryWorker worker --loglevel=info
    depends_on:
      - rabbitmq
      - db
    networks:
      - app-network
    # network_mode: host

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - rabbitmq
    networks:
      - app-network



volumes:
  postgres_data:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge
  