"""mais ajustes dos modelos

Revision ID: 1b459a4e1566
Revises: 1309f5188652
Create Date: 2025-04-29 17:50:02.483989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1b459a4e1566'
down_revision: Union[str, None] = '1309f5188652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('viacep_usuario_fkey', 'viacep', type_='foreignkey')
    op.drop_column('viacep', 'usuario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viacep', sa.Column('usuario', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('viacep_usuario_fkey', 'viacep', 'usuarios', ['usuario'], ['id'])
    # ### end Alembic commands ###
