"""coluna senha usuario

Revision ID: 4486d196602a
Revises: 5e01a84e2cc6
Create Date: 2025-04-19 02:04:15.110490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4486d196602a'
down_revision: Union[str, None] = '5e01a84e2cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('hashed_password', sa.String(), nullable=True))
    op.execute("UPDATE usuarios SET hashed_password = '1234'")
    op.alter_column('usuarios', 'hashed_password', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'hashed_password')
    # ### end Alembic commands ###
