"""Tabela de cep

Revision ID: 5339290e7b2c
Revises: 2f61fb9ce2e3
Create Date: 2025-04-28 17:25:22.873078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5339290e7b2c'
down_revision: Union[str, None] = '2f61fb9ce2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viacep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('complemento', sa.String(length=255), nullable=False),
    sa.Column('bairro', sa.String(length=255), nullable=False),
    sa.Column('localidade', sa.String(length=255), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('ibge', sa.String(length=10), nullable=False),
    sa.Column('gia', sa.String(length=10), nullable=False),
    sa.Column('ddd', sa.String(length=3), nullable=False),
    sa.Column('siafi', sa.String(length=10), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viacep_cep'), 'viacep', ['cep'], unique=True)
    op.create_index(op.f('ix_viacep_id'), 'viacep', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_viacep_id'), table_name='viacep')
    op.drop_index(op.f('ix_viacep_cep'), table_name='viacep')
    op.drop_table('viacep')
    # ### end Alembic commands ###
