"""ajustes tabela viacep

Revision ID: 53ac6ae91299
Revises: 421561b90e73
Create Date: 2025-04-29 16:53:54.859771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '53ac6ae91299'
down_revision: Union[str, None] = '421561b90e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viacep', sa.Column('estado', sa.String(length=255), nullable=False))
    op.add_column('viacep', sa.Column('regiao', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viacep', 'regiao')
    op.drop_column('viacep', 'estado')
    # ### end Alembic commands ###
