"""Tabela BrasilApiCep nome alteração

Revision ID: 565d46d57a74
Revises: 6af0172157bb
Create Date: 2025-05-01 22:10:43.799974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '565d46d57a74'
down_revision: Union[str, None] = '6af0172157bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brasil_api_cep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('neighborhood', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=200), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brasil_api_cep_id'), 'brasil_api_cep', ['id'], unique=False)
    op.drop_index('ix_enderecos_id', table_name='enderecos')
    op.drop_table('enderecos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enderecos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cep', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('neighborhood', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('street', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='enderecos_pkey')
    )
    op.create_index('ix_enderecos_id', 'enderecos', ['id'], unique=False)
    op.drop_index(op.f('ix_brasil_api_cep_id'), table_name='brasil_api_cep')
    op.drop_table('brasil_api_cep')
    # ### end Alembic commands ###
